// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr5LLb0Ho_xRH2nXBTQktsAqRJ0o3oIA4',
    appId: '1:505898186912:web:c8d7e77a97df2355e231c5',
    messagingSenderId: '505898186912',
    projectId: 'fruit-hub-e90a3',
    authDomain: 'fruit-hub-e90a3.firebaseapp.com',
    storageBucket: 'fruit-hub-e90a3.firebasestorage.app',
    measurementId: 'G-JLS9E9T8P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Ygv_uqke-IbUwzd1C2Id29DpaBAKVto',
    appId: '1:505898186912:android:7803fc343b653e99e231c5',
    messagingSenderId: '505898186912',
    projectId: 'fruit-hub-e90a3',
    storageBucket: 'fruit-hub-e90a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWxN_6UVeNckY5jfZBaE_2vDMUjJu6a4g',
    appId: '1:505898186912:ios:01d898957e374a0fe231c5',
    messagingSenderId: '505898186912',
    projectId: 'fruit-hub-e90a3',
    storageBucket: 'fruit-hub-e90a3.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWxN_6UVeNckY5jfZBaE_2vDMUjJu6a4g',
    appId: '1:505898186912:ios:01d898957e374a0fe231c5',
    messagingSenderId: '505898186912',
    projectId: 'fruit-hub-e90a3',
    storageBucket: 'fruit-hub-e90a3.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr5LLb0Ho_xRH2nXBTQktsAqRJ0o3oIA4',
    appId: '1:505898186912:web:2a092da373857607e231c5',
    messagingSenderId: '505898186912',
    projectId: 'fruit-hub-e90a3',
    authDomain: 'fruit-hub-e90a3.firebaseapp.com',
    storageBucket: 'fruit-hub-e90a3.firebasestorage.app',
    measurementId: 'G-MYQ9J6GX0W',
  );
}
